version: '3'

# volumes
volumes:
  laravel-auth-database_data:
    driver: local

# services
services:
  
  # Laravel service to provide app
  laravel-auth-app:
    container_name: ${APP_PHP_SERVICE}
    image: webdevops/php-nginx-dev:7.3
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MAX_EXECUTION_TIME=86400
      - PHP_DEBUGGER=xdebug
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUG_REMOTE_AUTOSTART=on
      - XDEBUG_REMOTE_CONNECT_BACK=on
    #      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
    ports:
      - ${APP_PHP_PORT}:80
  
  # MySQL database service
  laravel-auth-database:
    image: mysql:5.7
    container_name:  ${APP_MYSQL_SERVICE}
    volumes:
      - .:/var/www/app
      - laravel-auth-database_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - ${APP_MYSQL_PORT}:3306
